{
 "title": "iot_smartroom",
 "time": { "from": "2025-07-13T19:04:03.000Z", "to": "2025-07-13T19:07:09.000Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "light_actuator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iot_smarthome",
     "rawSql": "SELECT timestamp, value FROM iot_smarthome.light_actuator"
    }
   ]
  },
  {
   "title": "temperature_actuator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "iot_smarthome",
     "rawSql": "SELECT timestamp, value FROM iot_smarthome.temperature_actuator"
    }
   ]
  },
  {
   "title": "temperature_data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "iot_smarthome",
     "rawSql": "SELECT timestamp, value FROM iot_smarthome.temperature_data"
    }
   ]
  },
  {
   "title": "light_data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "iot_smarthome",
     "rawSql": "SELECT timestamp, value FROM iot_smarthome.light_data"
    }
   ]
  },
  {
   "title": "humidity_data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "iot_smarthome",
     "rawSql": "SELECT timestamp, value FROM iot_smarthome.humidity_data "
    }
   ]
  }
 ]
}